theme = "monokai_pro_machine"

[editor]
rulers=[80]
line-number = "relative"
bufferline = "multiple"
continue-comments = false

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name", "file-modification-indicator"]

[editor.file-picker]
hidden = false
