[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "python"
language-servers = ["pylsp"]
indent = { tab-width = 4, unit = "    " }

[language-server.pylsp.config.pylsp.plugins]
flake8 = {enabled = false}
autopep8 = {enabled = false}
pycodestyle = {enabled = false}
